global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:9090']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:9091']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:9092']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:9093']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:9094']

  - job_name: 'delivery-service'
    static_configs:
      - targets: ['delivery-service:9095']

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:9096']
