version: v1
managed:
  enabled: true
  go_package_prefix:
    default: github.com/afasari/shinkansen-commerce/gen/proto/go

plugins:
  # Generate Go code
  - name: go
    out: gen/proto/go
    opt: paths=source_relative

  - name: go-grpc
    out: gen/proto/go
    opt:
      - paths=source_relative
      - require_unimplemented_servers=false

  # Generate OpenAPI (Swagger) spec from proto files
  - name: openapiv2
    out: services/gateway/docs/api
    opt:
      - json_names_for_fields=false
      - allow_merge=true
      - merge_file_name=swagger
      - output_format=yaml
